apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: yamlr
    environment : rodrigo
  name: yamlr
spec:
  containers:
  - image: nginx
    name: yamlr
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
