name: CI - Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Exploring Actions3/Exploring Actions3.sln

      - name: Build the solution
        run: dotnet build ./Exploring Actions3/Exploring Actions3.sln

      - name: Run unit tests with report
        run: dotnet test ./Exploring Actions3/Exploring Actions3/Exploring Actions3.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./Exploring Actions3/TestController/WeatherForecastControllerTest.cs


